services:
  web:
    build: .
    volumes:
      - .:/code
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - stack.env
    depends_on:
      - db

  db:
      image: postgres:14
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static/
      - media_volume:/app/media
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
  media_volume: