services:
  web:
    build: .
    volumes:
      - .:/code
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8098"
    env_file:
      - stack.env
    depends_on:
      - db

  db:
      image: postgres:14
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nginx:
    build:
      context: ./nginx
    ports:
      - "8096:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static/
      - media_volume:/app/media
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
  media_volume: