# Generated by Django 4.2.13 on 2024-07-11 10:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200, unique=True)),
                ('missions', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_number', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('media', models.FileField(upload_to='uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'png', 'jpg', 'jpeg', 'gif'])])),
                ('validated', models.BooleanField(blank=True, null=True)),
                ('mission_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crazy88.missionlist')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.team')),
            ],
        ),
    ]
