# Generated by Django 4.2.13 on 2024-07-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RouteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=150)),
                ('section_html', models.TextField(blank=True, null=True)),
                ('additional_form', models.TextField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='RouteProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=1)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hike.route')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.team')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='route_sections',
            field=models.ManyToManyField(to='hike.routesection'),
        ),
        migrations.CreateModel(
            name='HintUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hike.routesection')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.team')),
            ],
            options={
                'unique_together': {('team', 'route_section')},
            },
        ),
    ]
