# Generated by Django 4.2.13 on 2024-07-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routesection',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
