# Generated by Django 4.2.13 on 2025-04-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_score',
            field=models.IntegerField(default=0),
        ),
    ]
