# Generated by Django 4.2.13 on 2025-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_team_team_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_bonus_score',
            field=models.IntegerField(default=0),
        ),
    ]
