# Generated by Django 4.2.13 on 2024-07-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_name', models.CharField(max_length=200)),
                ('poster_image', models.ImageField(upload_to='')),
                ('poster_date', models.DateField()),
            ],
        ),
    ]
