# Generated by Django 4.2.13 on 2025-04-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posters',
            new_name='Poster',
        ),
    ]
